name: build-app
run-name: ${{ github.actor }} fait des trucs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    # env: 
    #   REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: To lowercase
        run: echo "REPOSITORY=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Authentification
        run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/$REPOSITORY/tp2-connect:v0.1 .

      - name: Push Docker image
        run: docker push ghcr.io/$REPOSITORY/tp2-connect:v0.1